import { useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import {
  BadgeCheck,
  BriefcaseBusiness,
  CirclePlus,
  Eye,
  FileCheck2,
  Pencil,
  Search,
  Upload,
  UserCheck,
  UsersRound,
  X,
} from 'lucide-react'
import Badge from '../../components/common/Badge.jsx'
import Button from '../../components/common/Button.jsx'

const initialStaff = [
  { id: 1, employeeId: 'EMP-001', name: 'Neha Kapoor', phone: '+91 98765 43210', email: 'neha@salon.com', gender: 'Female', dob: '1997-03-14', address: 'Andheri West, Mumbai', role: 'Senior Hair Stylist', department: 'Hair', joiningDate: '2023-04-10', joiningTime: '09:00', shift: 'Morning', salary: '45000', emergencyName: 'Rahul Kapoor', emergencyPhone: '+91 98111 22334', identityType: 'Aadhaar Card', identityNumber: 'XXXX XXXX 4821', identityFile: 'neha-aadhaar.pdf', status: 'Active' },
  { id: 2, employeeId: 'EMP-002', name: 'Riya Mehta', phone: '+91 98234 56781', email: 'riya@salon.com', gender: 'Female', dob: '1995-08-22', address: 'Bandra East, Mumbai', role: 'Makeup Artist', department: 'Makeup', joiningDate: '2022-11-18', joiningTime: '09:30', shift: 'Morning', salary: '52000', emergencyName: 'Kiran Mehta', emergencyPhone: '+91 98220 11009', identityType: 'PAN Card', identityNumber: 'ABCDE1234F', identityFile: 'riya-pan.jpg', status: 'Active' },
  { id: 3, employeeId: 'EMP-003', name: 'Arjun Rao', phone: '+91 99876 54321', email: 'arjun@salon.com', gender: 'Male', dob: '1994-01-09', address: 'Powai, Mumbai', role: 'Menâ€™s Grooming Expert', department: 'Grooming', joiningDate: '2024-01-08', joiningTime: '14:00', shift: 'Evening', salary: '40000', emergencyName: 'Suresh Rao', emergencyPhone: '+91 99001 22334', identityType: 'Driving Licence', identityNumber: 'MH02 20210012345', identityFile: 'arjun-licence.pdf', status: 'Active' },
  { id: 4, employeeId: 'EMP-004', name: 'Pooja Das', phone: '+91 95432 10987', email: 'pooja@salon.com', gender: 'Female', dob: '1998-11-11', address: 'Dadar West, Mumbai', role: 'Beauty Therapist', department: 'Skin & Nails', joiningDate: '2024-06-15', joiningTime: '10:00', shift: 'Full Day', salary: '38000', emergencyName: 'Maya Das', emergencyPhone: '+91 98300 44556', identityType: 'Aadhaar Card', identityNumber: 'XXXX XXXX 1906', identityFile: 'pooja-aadhaar.png', status: 'Active' },
  { id: 5, employeeId: 'EMP-005', name: 'Vikram Shah', phone: '+91 94321 09876', email: 'vikram@salon.com', gender: 'Male', dob: '1992-05-30', address: 'Thane West, Mumbai', role: 'Salon Assistant', department: 'Operations', joiningDate: '2025-02-03', joiningTime: '14:30', shift: 'Evening', salary: '28000', emergencyName: 'Nita Shah', emergencyPhone: '+91 98980 11223', identityType: 'Voter ID', identityNumber: 'ABC1234567', identityFile: 'vikram-voter-id.pdf', status: 'On Leave' },
  { id: 6, employeeId: 'EMP-006', name: 'Simran Kaur', phone: '+91 93210 98765', email: 'simran@salon.com', gender: 'Female', dob: '1996-07-17', address: 'Malad West, Mumbai', role: 'Reception Manager', department: 'Front Desk', joiningDate: '2021-09-20', joiningTime: '09:00', shift: 'Full Day', salary: '48000', emergencyName: 'Harpreet Kaur', emergencyPhone: '+91 98100 77889', identityType: 'Passport', identityNumber: 'P1234567', identityFile: 'simran-passport.pdf', status: 'Active' },
]

const emptyStaff = { employeeId: '', name: '', phone: '', email: '', gender: 'Female', dob: '', address: '', role: '', department: '', joiningDate: '', joiningTime: '', shift: 'Morning', salary: '', emergencyName: '', emergencyPhone: '', identityType: 'Aadhaar Card', identityNumber: '', identityFile: '', status: 'Active' }

function FormField({ label, required, className = '', ...props }) {
  return <label className={className}><span className="mb-1.5 block text-sm font-semibold text-text">{label}{required && <span className="text-danger"> *</span>}</span><input required={required} className="h-11 w-full rounded-xl border border-border bg-surface px-4 text-sm text-text outline-none placeholder:text-text-muted focus:border-primary" {...props} /></label>
}

function FormSelect({ label, value, onChange, options }) {
  return <label><span className="mb-1.5 block text-sm font-semibold text-text">{label}</span><select value={value} onChange={onChange} className="h-11 w-full rounded-xl border border-border bg-surface px-4 text-sm text-text outline-none focus:border-primary">{options.map((option) => <option key={option}>{option}</option>)}</select></label>
}

function StaffModal({ mode, staff, onClose, onSave }) {
  const [form, setForm] = useState(staff ? { ...staff } : emptyStaff)
  const fileInputRef = useRef(null)
  const isView = mode === 'view'
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))

  if (isView) {
    const details = [
      ['Phone', staff.phone], ['Email', staff.email], ['Gender', staff.gender], ['Date of birth', staff.dob],
      ['Employee ID', staff.employeeId], ['Department', staff.department], ['Shift', staff.shift], ['Joining date', staff.joiningDate], ['Joining time', staff.joiningTime],
      ['Address', staff.address], ['Emergency contact', `${staff.emergencyName} Â· ${staff.emergencyPhone}`],
    ]
    return <AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} onMouseDown={onClose} className="fixed inset-0 z-50 flex items-center justify-center bg-secondary/45 p-4"><motion.div initial={{ y: 14, scale: 0.97 }} animate={{ y: 0, scale: 1 }} onMouseDown={(event) => event.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-3xl border border-border bg-card shadow-2xl"><div className="flex items-start justify-between border-b border-border px-6 py-5"><div><h2 className="text-lg font-extrabold text-text">Staff details</h2><p className="mt-1 text-sm text-text-muted">Employment, contact and identity information.</p></div><button type="button" onClick={onClose} className="flex size-9 items-center justify-center rounded-full border border-border text-text-muted"><X className="size-4" /></button></div><div className="max-h-[72vh] overflow-y-auto p-6 premium-scrollbar"><div className="flex flex-col gap-5 rounded-2xl bg-background p-5 sm:flex-row sm:items-center"><span className="flex size-16 items-center justify-center rounded-2xl bg-primary/10 text-xl font-extrabold text-primary">{staff.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><div className="flex-1"><h3 className="text-xl font-extrabold text-text">{staff.name}</h3><p className="mt-1 text-sm text-text-muted">{staff.role} Â· {staff.department}</p></div><Badge variant={staff.status === 'Active' ? 'success' : 'warning'}>{staff.status}</Badge></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{details.map(([label, value]) => <div key={label} className="rounded-2xl border border-border p-4"><p className="text-xs font-semibold text-text-muted">{label}</p><p className="mt-1.5 text-sm font-bold text-text">{value || 'Not provided'}</p></div>)}</div><div className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-center gap-2 text-primary"><FileCheck2 className="size-5" /><h4 className="text-sm font-bold">Identity verification</h4></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-text-muted">Document type</p><p className="mt-1 text-sm font-bold text-text">{staff.identityType}</p></div><div><p className="text-xs text-text-muted">Identity number</p><p className="mt-1 text-sm font-bold text-text">{staff.identityNumber}</p></div><div><p className="text-xs text-text-muted">Uploaded file</p><p className="mt-1 truncate text-sm font-bold text-primary">{staff.identityFile || 'No document'}</p></div></div></div></div></motion.div></motion.div></AnimatePresence>
  }

  const submit = (event) => { event.preventDefault(); onSave(form) }
  const selectFile = (event) => { const file = event.target.files?.[0]; if (file) update('identityFile', file.name) }
  return <AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} onMouseDown={onClose} className="fixed inset-0 z-50 flex items-center justify-center bg-secondary/45 p-4"><motion.div initial={{ y: 14, scale: 0.97 }} animate={{ y: 0, scale: 1 }} onMouseDown={(event) => event.stopPropagation()} className="max-h-[92vh] w-full max-w-4xl overflow-hidden rounded-3xl border border-border bg-card shadow-2xl"><div className="flex items-start justify-between border-b border-border px-6 py-5"><div><h2 className="text-lg font-extrabold text-text">{staff ? 'Edit staff member' : 'Add staff member'}</h2><p className="mt-1 text-sm text-text-muted">Personal, employment and identity details.</p></div><button type="button" onClick={onClose} className="flex size-9 items-center justify-center rounded-full border border-border text-text-muted"><X className="size-4" /></button></div><form onSubmit={submit} className="max-h-[78vh] overflow-y-auto p-6 premium-scrollbar">
    <h3 className="text-sm font-extrabold text-text">Personal information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><FormField label="Full name" required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Employee full name" /><FormField label="Mobile number" required value={form.phone} onChange={(event) => update('phone', event.target.value)} placeholder="Mobile number" /><FormField label="Email" type="email" value={form.email} onChange={(event) => update('email', event.target.value)} placeholder="Email address" /><FormSelect label="Gender" value={form.gender} onChange={(event) => update('gender', event.target.value)} options={['Female', 'Male', 'Other']} /><FormField label="Date of birth" type="date" value={form.dob} onChange={(event) => update('dob', event.target.value)} /><FormField label="Address" value={form.address} onChange={(event) => update('address', event.target.value)} placeholder="Current address" /></div>
    <h3 className="mt-7 border-t border-border pt-6 text-sm font-extrabold text-text">Employment information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><FormField label="Employee ID" required value={form.employeeId} onChange={(event) => update('employeeId', event.target.value)} placeholder="e.g. EMP-007" /><FormField label="Role / designation" required value={form.role} onChange={(event) => update('role', event.target.value)} placeholder="e.g. Hair Stylist" /><FormField label="Department" required value={form.department} onChange={(event) => update('department', event.target.value)} placeholder="Department" /><FormField label="Joining date" required type="date" value={form.joiningDate} onChange={(event) => update('joiningDate', event.target.value)} /><FormField label="Joining time" required type="time" value={form.joiningTime} onChange={(event) => update('joiningTime', event.target.value)} /><FormSelect label="Work shift" value={form.shift} onChange={(event) => update('shift', event.target.value)} options={['Morning', 'Evening', 'Full Day']} /><FormField label="Monthly salary" type="number" value={form.salary} onChange={(event) => update('salary', event.target.value)} placeholder="Salary amount" /><FormSelect label="Employment status" value={form.status} onChange={(event) => update('status', event.target.value)} options={['Active', 'On Leave', 'Inactive']} /></div>
    <h3 className="mt-7 border-t border-border pt-6 text-sm font-extrabold text-text">Emergency contact</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormField label="Contact person" value={form.emergencyName} onChange={(event) => update('emergencyName', event.target.value)} placeholder="Full name" /><FormField label="Emergency phone" value={form.emergencyPhone} onChange={(event) => update('emergencyPhone', event.target.value)} placeholder="Mobile number" /></div>
    <h3 className="mt-7 border-t border-border pt-6 text-sm font-extrabold text-text">Identity verification</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormSelect label="Identity type" value={form.identityType} onChange={(event) => update('identityType', event.target.value)} options={['Aadhaar Card', 'PAN Card', 'Passport', 'Driving Licence', 'Voter ID']} /><FormField label="Identity number" required value={form.identityNumber} onChange={(event) => update('identityNumber', event.target.value)} placeholder="Document number" /></div><input ref={fileInputRef} type="file" accept="image/png,image/jpeg,application/pdf" onChange={selectFile} className="hidden" /><button type="button" onClick={() => fileInputRef.current?.click()} className="mt-4 flex w-full items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-border bg-background px-5 py-6 text-sm font-semibold text-text-muted transition-colors hover:border-primary/40 hover:text-primary"><Upload className="size-5" />{form.identityFile ? `Selected: ${form.identityFile}` : 'Upload identity image or PDF'}</button><p className="mt-2 text-xs text-text-muted">Frontend-only demo: the file name remains in memory until the page refreshes.</p>
    <div className="mt-6 flex justify-end gap-3 border-t border-border pt-5"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">{staff ? 'Save changes' : 'Add staff member'}</Button></div>
  </form></motion.div></motion.div></AnimatePresence>
}

function Staff() {
  const [staffMembers, setStaffMembers] = useState(initialStaff)
  const [search, setSearch] = useState('')
  const [gender, setGender] = useState('')
  const [status, setStatus] = useState('')
  const [modal, setModal] = useState(null)

  const filteredStaff = useMemo(() => { const query = search.trim().toLowerCase(); return staffMembers.filter((staff) => (!query || [staff.employeeId, staff.name, staff.phone, staff.role, staff.department].some((value) => value.toLowerCase().includes(query))) && (!gender || staff.gender === gender) && (!status || staff.status === status)) }, [staffMembers, search, gender, status])
  const activeCount = staffMembers.filter((staff) => staff.status === 'Active').length
  const verifiedCount = staffMembers.filter((staff) => staff.identityFile).length
  const summary = [{ label: 'Total staff', value: staffMembers.length, icon: UsersRound, tone: 'bg-primary/10 text-primary' }, { label: 'Active staff', value: activeCount, icon: UserCheck, tone: 'bg-success/10 text-success' }, { label: 'Departments', value: new Set(staffMembers.map((staff) => staff.department)).size, icon: BriefcaseBusiness, tone: 'bg-info/10 text-info' }, { label: 'Identity uploaded', value: verifiedCount, icon: BadgeCheck, tone: 'bg-warning/10 text-warning' }]
  const saveStaff = (form) => { const editingStaff = modal?.staff; if (editingStaff) setStaffMembers((current) => current.map((staff) => staff.id === editingStaff.id ? { ...staff, ...form } : staff)); else setStaffMembers((current) => [...current, { ...form, id: Date.now() }]); setModal(null) }
  const clearFilters = () => { setSearch(''); setGender(''); setStatus('') }

  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-extrabold tracking-tight text-text">Staff management</h1><p className="mt-1 text-sm text-text-muted">Manage employee profiles, joining records and identity documents.</p></div><Button type="button" onClick={() => setModal({ mode: 'add' })}><CirclePlus className="size-4" />Add staff member</Button></div>
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{summary.map(({ label, value, icon: Icon, tone }, index) => <motion.article key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} whileHover={{ y: -3 }} className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-text-muted">{label}</p><p className="mt-2 text-2xl font-extrabold text-text">{String(value).padStart(2, '0')}</p></div><span className={`flex size-11 items-center justify-center rounded-xl ${tone}`}><Icon className="size-5" /></span></div></motion.article>)}</div>
    <section className="rounded-2xl border border-border bg-card p-4 shadow-soft"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(260px,1fr)_180px_180px_auto]"><div className="relative"><Search className="pointer-events-none absolute top-1/2 left-3.5 size-4 -translate-y-1/2 text-text-muted" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employee ID, name, phone or role" className="h-11 w-full rounded-xl border border-border bg-surface pr-4 pl-10 text-sm outline-none placeholder:text-text-muted focus:border-primary" /></div><select value={gender} onChange={(event) => setGender(event.target.value)} className="h-11 rounded-xl border border-border bg-surface px-4 text-sm font-semibold outline-none focus:border-primary"><option value="">All genders</option><option>Female</option><option>Male</option><option>Other</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-border bg-surface px-4 text-sm font-semibold outline-none focus:border-primary"><option value="">All statuses</option><option>Active</option><option>On Leave</option><option>Inactive</option></select><Button type="button" variant="outline" onClick={clearFilters}>Clear filters</Button></div></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-bold text-text">Staff directory</h2><p className="mt-0.5 text-xs text-text-muted">{filteredStaff.length} matching staff members</p></div><div className="overflow-x-auto premium-scrollbar"><table className="w-full min-w-[1250px] text-left"><thead className="bg-background"><tr className="border-b border-border text-xs font-bold uppercase tracking-wide text-text-muted">{['Employee ID', 'Staff member', 'Contact', 'Gender', 'Role', 'Department', 'Joining date & time', 'Shift', 'Identity', 'Status', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3.5">{heading}</th>)}</tr></thead><tbody>{filteredStaff.map((staff) => <tr key={staff.id} className="border-b border-border/70 last:border-0 hover:bg-primary/[0.035]"><td className="px-5 py-4 text-sm font-bold text-primary">{staff.employeeId}</td><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{staff.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><p className="text-sm font-bold text-text">{staff.name}</p></div></td><td className="px-5 py-4"><p className="text-sm text-text">{staff.phone}</p><p className="text-xs text-text-muted">{staff.email}</p></td><td className="px-5 py-4 text-sm text-text-muted">{staff.gender}</td><td className="px-5 py-4 text-sm font-semibold text-text">{staff.role}</td><td className="px-5 py-4 text-sm text-text-muted">{staff.department}</td><td className="px-5 py-4"><p className="text-sm text-text-muted">{staff.joiningDate}</p><p className="text-xs font-semibold text-text">{staff.joiningTime}</p></td><td className="px-5 py-4 text-sm text-text">{staff.shift}</td><td className="px-5 py-4"><Badge variant={staff.identityFile ? 'info' : 'outline'}>{staff.identityFile ? 'Uploaded' : 'Missing'}</Badge></td><td className="px-5 py-4"><Badge variant={staff.status === 'Active' ? 'success' : staff.status === 'On Leave' ? 'warning' : 'outline'}>{staff.status}</Badge></td><td className="px-5 py-4"><div className="flex gap-2"><button type="button" onClick={() => setModal({ mode: 'view', staff })} className="flex size-8 items-center justify-center rounded-lg border border-border text-text-muted hover:text-primary" aria-label={`View ${staff.name}`}><Eye className="size-4" /></button><button type="button" onClick={() => setModal({ mode: 'edit', staff })} className="flex size-8 items-center justify-center rounded-lg border border-border text-text-muted hover:text-primary" aria-label={`Edit ${staff.name}`}><Pencil className="size-4" /></button></div></td></tr>)}{!filteredStaff.length && <tr><td colSpan="11" className="px-5 py-14 text-center text-sm font-semibold text-text-muted">No staff members match these filters.</td></tr>}</tbody></table></div></section>
    {modal ? <StaffModal mode={modal.mode} staff={modal.staff ?? null} onClose={() => setModal(null)} onSave={saveStaff} /> : null}
  </div>
}

export default Staff


