export const ROUTE_PATHS = Object.freeze({
  home: '/',
  about: '/about',
  services: '/services',
  howItWorks: '/how-it-works',
  products: '/products',
  productDetails: '/products/:productId',
  cart: '/cart',
  wishlist: '/wishlist',
  account: '/account',
  accountAppointments: '/account/appointments',
  accountAppointmentDetails: '/account/appointments/:appointmentId',
  accountOrders: '/account/orders',
  accountWishlist: '/account/wishlist',
  accountProfile: '/account/profile',
  accountSettings: '/account/settings',
  login: '/login',
  dashboard: '/dashboard',
  appointments: '/appointments',
  calendar: '/calendar',
  customers: '/customers',
  staff: '/staff',
  dashboardServices: '/dashboard/services',
  dashboardProducts: '/dashboard/products',
  settings: '/settings',
  settingsAppearance: '/settings/appearance',
  settingsLandingPage: '/settings/landing-page',
})
