export const ROUTE_PATHS = Object.freeze({
  home: '/',
  about: '/about',
  services: '/services',
  howItWorks: '/how-it-works',
  products: '/products',
  productDetails: '/products/:productId',
  cart: '/cart',
  wishlist: '/wishlist',
  login: '/login',
  dashboard: '/dashboard',
  appointments: '/appointments',
  calendar: '/calendar',
  customers: '/customers',
  staff: '/staff',
  dashboardServices: '/dashboard/services',
  dashboardProducts: '/dashboard/products',
  settings: '/settings',
  settingsAppearance: '/settings/appearance',
  settingsLandingPage: '/settings/landing-page',
})
