// Base (light-context) color sets. Dark mode is a separate override layer — see ThemeContext.jsx.
export const themePresets = [
  {
    id: 'default',
    name: 'Default',
    colors: {
      primary: '#6c4ee3',
      secondary: '#241c4e',
      accent: '#f0b84b',
      background: '#faf9fc',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#1b1730',
      navbar: '#ffffff',
      border: '#e7e4f2',
      text: '#16132b',
      textMuted: '#6b6785',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    colors: {
      primary: '#0ea5e9',
      secondary: '#0c4a6e',
      accent: '#22d3ee',
      background: '#f5fafd',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#082f49',
      navbar: '#ffffff',
      border: '#dbeafe',
      text: '#0c1e2e',
      textMuted: '#5b7a8c',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald',
    colors: {
      primary: '#10b981',
      secondary: '#064e3b',
      accent: '#34d399',
      background: '#f4faf7',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#052e23',
      navbar: '#ffffff',
      border: '#d8f0e4',
      text: '#0c1f18',
      textMuted: '#5c7c70',
    },
  },
  {
    id: 'royal',
    name: 'Royal',
    colors: {
      primary: '#7c3aed',
      secondary: '#1e1b4b',
      accent: '#fbbf24',
      background: '#faf9fd',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#150f36',
      navbar: '#ffffff',
      border: '#e9e4fb',
      text: '#160f2e',
      textMuted: '#6a6489',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      primary: '#f97316',
      secondary: '#7c2d12',
      accent: '#fb7185',
      background: '#fdf8f5',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#3a1408',
      navbar: '#ffffff',
      border: '#fbe2d3',
      text: '#2a1710',
      textMuted: '#8a6e60',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    colors: {
      primary: '#4f46e5',
      secondary: '#0f0f1a',
      accent: '#818cf8',
      background: '#f6f6f9',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#0a0a12',
      navbar: '#ffffff',
      border: '#e3e3ec',
      text: '#111118',
      textMuted: '#68687d',
    },
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    colors: {
      primary: '#0f172a',
      secondary: '#334155',
      accent: '#38bdf8',
      background: '#fafafa',
      surface: '#ffffff',
      card: '#ffffff',
      sidebar: '#18181b',
      navbar: '#ffffff',
      border: '#e4e4e7',
      text: '#18181b',
      textMuted: '#71717a',
    },
  },
]

export const defaultPreset = themePresets[0]

export const darkModeOverrides = {
  background: '#0b0a14',
  surface: '#14121f',
  card: '#17152a',
  navbar: '#14121f',
  border: '#2a273f',
  text: '#f5f4fa',
  textMuted: '#9490b3',
}

export const themeColorKeys = Object.keys(defaultPreset.colors)
